# -*- coding: utf-8 -*-
"""Oasis Task-1 Iris Flower.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LUHkAu4wbkJD29k8PGfXXn9SEEoe9XcX

**BAKALI JABEEN MOHAMMEDTOFFIQ**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Iris.csv")
df.head()

# Delete the column
df=df.drop(columns="Id")

df.head()

# to display stats about the data
df.describe()

# basic  info of datatype in dataset
df.info()

# Display the number of samples on each class
df["Species"].value_counts()

# Check for the null values
df.isnull().sum()

# histograms
df['SepalLengthCm'].hist()

df['SepalWidthCm'].hist()

df['PetalLengthCm'].hist()

df['PetalWidthCm'].hist()

sns.pairplot(df,hue='Species')

# Compute the correlation matrix
df.corr()

# display the correlation matrix using a heatmap
corr = df.corr()
fig, ax = plt.subplots(figsize=(5, 4))
sns.heatmap(corr, annot=True, ax=ax, cmap='coolwarm')